In [18]:
%matplotlib inline
import pandas as pd
import numpy as np
import os
import stanfordnlp
from tqdm import tqdm

In [2]:
path_to_data = '/home/dafne/shared/FilterBubble/topic-modeling/'
fname = os.path.join(path_to_data, 'texts_rens.csv')

data = pd.read_csv(fname)

In [3]:
len(data), data.aid.nunique()

(98735, 97443)

In [5]:
data[data.aid.isna()]

Empty DataFrame
Columns: [aid, id, date, outlet, headline, text, economic, conflict, human, topic_all, topic_six]
Index: []

In [11]:
nr_aids = data.groupby('aid').count()['id']
data[data.aid.isin(nr_aids[nr_aids>1].index)]

,aid,id,date,outlet,headline,text,economic,conflict,human,topic_all,topic_six
99,74188329,#10026 @37512482 +4731,2001-05-02,NRC Handelsblad,Chinese maffia niet te zien,Vier jaar lang bracht de Rotterdamse politie d...,0.0,1.0,1.0,12.0,5.0
100,74188329,#10026 @37512482 +4731,2001-05-02,NRC Handelsblad,Chinese maffia niet te zien,Vier jaar lang bracht de Rotterdamse politie d...,0.0,1.0,1.0,12.0,5.0
200,74187799,#10056 @37614086 +2698,2001-04-26,NRC Handelsblad,Bromfiets op de weg: meer doden,In 2000 zijn 111 bromfietsers overleden door e...,0.0,0.0,0.0,10.0,6.0
201,74187799,#10056 @37614086 +2698,2001-04-26,NRC Handelsblad,Bromfiets op de weg: meer doden,In 2000 zijn 111 bromfietsers overleden door e...,0.0,0.0,0.0,10.0,6.0
301,74188379,#10086 @37698823 +2845,2001-04-20,NRC Handelsblad,Kamer verwerpt motie tegen Borst,Een motie om minister Borst (Volksgezondheid) ...,0.0,1.0,0.0,20.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...
98477,74187741,#9923 @37178189 +4404,2001-05-28,NRC Handelsblad,Niet voor kijkers,Sommige uitzendingen zijn niet voor kijkers be...,0.0,1.0,1.0,23.0,99.0
98577,74240601,#9953 @34555193 +10665,2001-05-09,de Volkskrant,Een taart voor Freddie Mercury,Tien jaar geleden stierf zanger Freddie Mercur...,0.0,1.0,1.0,23.0,2.0
98578,74240601,#9953 @34555193 +10665,2001-05-09,de Volkskrant,Een taart voor Freddie Mercury,Tien jaar geleden stierf zanger Freddie Mercur...,0.0,1.0,1.0,23.0,2.0
98678,74188973,#9982 @37357455 +3448,2001-05-12,NRC Handelsblad,Toezichthouder declareerde dubbel,Bestuurslid J. van Doorne van de Commissie Toe...,1.0,1.0,1.0,20.0,2.0
98679,74188973,#9982 @37357455 +3448,2001-05-12,NRC Handelsblad,Toezichthouder declareerde dubbel,Bestuurslid J. van Doorne van de Commissie Toe...,1.0,1.0,1.0,20.0,2.0

In [14]:
data_deduplicated = data.groupby('aid').first()

In [15]:
nlp = stanfordnlp.Pipeline(lang='nl')

Use device: cpu
---
Loading: tokenize
With settings:
{'model_path': '/home/dafne/stanfordnlp_resources/nl_alpino_models/nl_alpino_tokenizer.pt', 'lang': 'nl', 'shorthand': 'nl_alpino', 'mode': 'predict'}
---
Loading: pos
With settings:
{'model_path': '/home/dafne/stanfordnlp_resources/nl_alpino_models/nl_alpino_tagger.pt', 'pretrain_path': '/home/dafne/stanfordnlp_resources/nl_alpino_models/nl_alpino.pretrain.pt', 'lang': 'nl', 'shorthand': 'nl_alpino', 'mode': 'predict'}
---
Loading: lemma
With settings:
{'model_path': '/home/dafne/stanfordnlp_resources/nl_alpino_models/nl_alpino_lemmatizer.pt', 'lang': 'nl', 'shorthand': 'nl_alpino', 'mode': 'predict'}
Building an attentional Seq2Seq model...
Using a Bi-LSTM encoder
Using soft attention for LSTM.
Finetune all embeddings.
[Running seq2seq lemmatizer with edit classifier]
---
Loading: depparse
With settings:
{'model_path': '/home/dafne/stanfordnlp_resources/nl_alpino_models/nl_alpino_parser.pt', 'pretrain_path': '/home/dafne/stanfordnlp_resources/nl_alpino_models/nl_alpino.pretrain.pt', 'lang': 'nl', 'shorthand': 'nl_alpino', 'mode': 'predict'}
Done loading processors!
---

In [ ]:
import warnings
warnings.simplefilter('ignore')

fpath_connl = '/home/dafne/shared/FilterBubble/topic-modeling/parsed_stanfordnlp/'

for aid, row in tqdm(data_deduplicated.iterrows()):
    doc = nlp(row['text'])
    fn_out = os.path.join(fpath_connl, str(aid)+'.connl')
    with open(fn_out, 'w') as f:
        f.write(doc.conll_file.conll_as_string())

1204it [2:02:21, 17.61s/it]